name: Build Leaf for x86_64-limine

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --progress=plain -t leaf-builder .

      - name: Create container from image
        id: create-container
        run: |
          docker create --name leaf-container leaf-builder
          docker cp leaf-container:/leaf/release/ ./release
          docker rm leaf-container

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Leaf-release
          path: release
