name: Build Leaf for x86_64-limine

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: |
          ./docker_build.sh


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: leaf-$(date +'%Y-%m-%d')-builds
          path: release
